### ISSUE TITLE
Stop updating GCC prerequisites packages on AT next

### ISSUE THREAD

**Issue by er-1** [advancetoolchain/advance-toolchain#1015]
In order to build GCC, the script https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=contrib/download_prerequisites downloads a few packages that are also provided by AT but with newer versions. This could lead to hard-to-diagnose issues.

Project | AT 12.0-0 | download_prerequisites
--------|-----------|-----------------------
gmp     | 6.1.2     | 6.1.0
mpfr    | 4.0.2     | 3.1.4
mpc     | 1.1.0     | 1.0.3

We agree to continue as we did for AT 12.0. but not newer versions.

**Comment by gftg85** [comment]
So, these commits turn AT-13.0's `sources` files for _mpc_ and _mpfr_ into symlinks to AT-12.0's.  And the expectation is that AT-12.0's _mpc_ and _mpfr_ are no longer updated by Cherbot's automatic updates.  Is my understanding correct?

I don't understand how the file/symlink change in the patch would stop the updates, as the commit message states/implies, but I think I understand what is meant, i.e.: that **since** we are not going to update _mpc_ and _mpfr_, we **can reuse** their `sources` file from AT-12.0 in AT-13.0.  Please let me know if that's not the case.
