### ISSUE TITLE
Regression: SPHDE stopped building in AT 9.0 SLES 12

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#126]
The last known working build is 403f8d610bf43a2760a47be3aba7254b08c1a3d4.
Commit ID 8813c7c8b2c0241485669057016be3473b7e871d started to fail.

```
Makefile:1321: recipe for target '/home/tcbot/bot-slave/at/src/at9.0-6-alpha.suse-12_ppc64le_ppc64le/receipts/libsphde_1-64.b.rcpt' failed
make: *** [/home/tcbot/bot-slave/at/src/at9.0-6-alpha.suse-12_ppc64le_ppc64le/receipts/libsphde_1-64.b.rcpt] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by rpsene** [comment]
There was missing one dependency at SLES12 build machine: glibc-devel-static. I'm not sure this is the root problem, but my stand alone build of sphde worked after this installation.

**Comment by tuliom** [comment]
Installing glibc-devel-static shouldn't affect an AT build because AT provides its own glibc.
If it does build, we have another bug.

**Comment by racardoso** [comment]
I guess this problem was been solved. I've "tipped"  on this problem when I was make AT 9.0-6 releases, libsphed was failing because when our cache script caches libsphed package it was .gitignore the man file. When AT run the `make install` from `libsphed/make` it can't find the man file and install fails. This was already fixed on our cache script (seem our internal repo).

**Comment by tuliom** [comment]
Closing per the previous comment.
